/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DepositAndPlaceOrder extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DepositAndPlaceOrder;
  clone(): DepositAndPlaceOrder;
  methods: {
    creditAuction(): NonPayableTransactionObject<string>;

    depositAndPlaceOrder(
      _minBuyAmounts: (number | string | BN)[],
      _prevSellOrders: (string | number[])[],
      referralCode: string
    ): PayableTransactionObject<string>;

    nativeTokenWrapper(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
