/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { AuctionClaimer } from "./AuctionClaimer";
export type { CreditAuction } from "./CreditAuction";
export type { CreditPair } from "./CreditPair";
export type { CreditPosition } from "./CreditPosition";
export type { CreditRouter } from "./CreditRouter";
export type { CreditRouterWL } from "./CreditRouterWL";
export type { CreditStaking } from "./CreditStaking";
export type { DepositAndPlaceOrder } from "./DepositAndPlaceOrder";
export type { Erc20 } from "./Erc20";
export type { Erc721 } from "./Erc721";
export type { Faucet } from "./Faucet";
export type { LockedDebt } from "./LockedDebt";
export type { LpFarming } from "./LpFarming";
export type { Multicall } from "./Multicall";
export type { ReferralRewardManager } from "./ReferralRewardManager";
export type { SpinPurchaser } from "./SpinPurchaser";
export type { TestnetFaucet } from "./TestnetFaucet";
